# Generated by Django 4.1 on 2022-08-18 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
