# Generated by Django 4.1 on 2022-08-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApi', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task',
            field=models.TextField(default='Описание', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=300, verbose_name='Краткое описание'),
        ),
    ]
